name: 3D-contrib-svg
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      # 1 渲染到 _output 目录
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          user: jiugulixiaoniu           # 你的用户名
          theme: night-green              # 要的主题
          output_dir: ./profile-3d-contrib

      # 2 如果有文件变化就提交
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git diff --staged --quiet || (git commit -m "chore: generate 3D contrib" && git push)
