name: 3D-contrib-svg

on:
  schedule: [{cron: "0 16 * * *"}]   # 每天 00:00(UTC+8)
  workflow_dispatch:                # 手动运行按钮
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          USERNAME: jiugulixiaoniu      
          SVG_THEME: night-green            
          BRANCH_NAME: main
          COMMIT_MSG: "chore: generated"
          FOLDER: profile-3d-contrib        
